apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: docker-devfile-sample-hello-world-npxq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: docker-devfile-sample-hello-world-npxq
    app.kubernetes.io/part-of: test-app-cpie
  name: docker-devfile-sample-hello-world-npxq
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: docker-devfile-sample-hello-world-npxq
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: docker-devfile-sample-hello-world-npxq
    spec:
      containers:
      - image: quay.io/rh-gitops-bot/build-e2e-yjnh-tenant/test-app-cpie/docker-devfile-sample-hello-world-npxq@sha256:b61d6e0a23fb7200282a3330af6fc7f11c4440f3d99eb3421a9908f97d0cb891
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8081
        resources: {}
status: {}
